FROM odoo:17

# Copy custom addons
COPY odoo_addons /mnt/extra-addons

# Replace the webclient templates to remove Odoo branding
COPY patches/webclient_templates.xml /usr/lib/python3/dist-packages/odoo/addons/web/views/webclient_templates.xml



