#!/bin/bash
# Admin Panel Setup Guide

echo "=== Odoo SaaS Admin Panel Setup ==="
echo ""
echo "The admin panel has been created with the following components:"
echo ""
echo "1. Backend API (FastAPI)"
echo "   Location: app/api/admin.py"
echo "   Endpoints:"
echo "   - POST /api/admin/login - Admin authentication"
echo "   - GET /api/admin/dashboard - Dashboard overview"
echo "   - GET /api/admin/tenants - List all tenants"
echo "   - POST /api/admin/tenants - Create new tenant"
echo "   - GET /api/admin/tenants/{tenant_id} - Get tenant details"
echo "   - PUT /api/admin/tenants/{tenant_id} - Update tenant"
echo "   - DELETE /api/admin/tenants/{tenant_id} - Delete tenant"
echo "   - GET /api/admin/tenants/{tenant_id}/metrics - Tenant metrics"
echo ""
echo "2. Frontend Dashboard (React)"
echo "   Location: app/static/"
echo "   Files:"
echo "   - index.html - Main entry point"
echo "   - dashboard.jsx - React component"
echo "   - dashboard.css - Styling"
echo ""
echo "3. Database Models"
echo "   Location: app/models/"
echo "   Uses existing: Tenant, Order, Product models"
echo ""
echo "4. Schemas"
echo "   Location: app/schemas/admin.py"
echo "   Models: TenantCreate, TenantUpdate, TenantResponse, etc."
echo ""
echo "=== Configuration ==="
echo ""
echo "Admin Password (from .env): ADMIN_PASSWORD"
echo "Default: admin123"
echo ""
echo "Update in .env:"
echo "ADMIN_PASSWORD=your-secure-password"
echo ""
echo "=== Running the Application ==="
echo ""
echo "1. Build Docker image:"
echo "   docker-compose build"
echo ""
echo "2. Start services:"
echo "   docker-compose up -d"
echo ""
echo "3. Access admin panel:"
echo "   - Admin Dashboard: http://localhost:9000/admin"
echo "   - API Swagger: http://localhost:9000/docs"
echo ""
echo "4. Login with password:"
echo "   - Open http://localhost:9000/admin"
echo "   - Use password from ADMIN_PASSWORD env var"
echo ""
echo "=== Features ==="
echo ""
echo "✓ Tenant Management (Create, Read, Update, Delete)"
echo "✓ Dashboard Overview (total tenants, orders, revenue)"
echo "✓ Tenant Metrics (orders, revenue, products)"
echo "✓ Responsive Design"
echo "✓ JWT Token Authentication"
echo "✓ Database Integration"
echo ""
echo "=== Next Steps ==="
echo ""
echo "1. Update ADMIN_PASSWORD in .env file"
echo "2. Update CORS origins in app/main.py if deploying to production"
echo "3. Customize dashboard styling in app/static/dashboard.css"
echo "4. Add metrics/charts using charting library (e.g., Chart.js)"
echo ""
